
project_id = "ai-trading-platform"

[api]
port = 54321
host = "127.0.0.1"
schema = "public"
extra_search_path = "public,extensions"
max_rows = 1000

[functions]
[functions.ai-assistant]
verify_jwt = false

[functions.connect-broker]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

