// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jekbwvdktltfokbalnuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impla2J3dmRrdGx0Zm9rYmFsbnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzEwMjMsImV4cCI6MjA1OTU0NzAyM30.P9eAtGZhR6hxgQBXMwDqQUZqj4mjG2e1iJlkN1BT6G8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);